export default [
    { "label": "Fuel Oil, No. 2, New York", "value": "WSJ/FUELOIL" },
    { "label": "Pork Bellies, 12-14 lbs, Mid US", "value": "WSJ/PBELLY" },
    { "label": "Crude Oil, West Texas Sour, Midlands TX", "value": "WSJ/OIL_WTSOUR" },
    { "label": "Wool, 64's, Staple, Terr. Delivery", "value": "WSJ/WOOL" },
    { "label": "Raw Cane Sugar, World Price, FOB", "value": "WSJ/SUGAR_CANE" },
    { "label": "Crude Oil, Forties Blend, North Sea", "value": "WSJ/OIL_40S" },
    { "label": "Crude Oil, Louisiana Sweet, St. James LA", "value": "WSJ/OIL_LASWT" },
    { "label": "Gasoline, California RBOB, Regular LA", "value": "WSJ/GAS_CARBOB" },
    { "label": "Propane, wet-tet, Mont Belvieu, Texas", "value": "WSJ/PROP_WTET" },
    { "label": "Gasoline, Reformulated Blendstock, Regular NY", "value": "WSJ/GAS_RBR" },
    { "label": "Crude Oil, West Texas Intermediate, Cushing OK", "value": "WSJ/OIL_WTI" },
    { "label": "Hominy feed, Central Illinois", "value": "WSJ/HOMINY" },
    { "label": "Gasoline, Conventional, Regular NY", "value": "WSJ/GAS_CR" },
    { "label": "Steers, Texas-Oklahoma average", "value": "WSJ/STEERS" },
    { "label": "Aluminum, LME", "value": "WSJ/AL_LME" },
    { "label": "Crude Oil, Brent Blend, North Sea", "value": "WSJ/OIL_BRENT" },
    { "label": "Diesel Fuel, NY Harbor Low Sulfur", "value": "WSJ/DIESEL_LS" },
    { "label": "Crude Oil, Urals-Mediterranean (Russian Export Blend)", "value": "WSJ/OIL_URALS" },
    { "label": "Crude Oil, Bonny Light, Nigeria", "value": "WSJ/OIL_BONNY" },
    { "label": "Propane, non-tet, Mont Belvieu, Texas", "value": "WSJ/PROP_NTET" },
    { "label": "Aluminum, Comex", "value": "WSJ/AL_CMX" },
    { "label": "Hides, heavy native steers, FOB", "value": "WSJ/HIDES_LB" },
    { "label": "Gasoline, Reformulated Blendstock, Premium NY", "value": "WSJ/GAS_RBP" },
    { "label": "Hogs, Sioux Falls SD average", "value": "WSJ/HOGS_SF" },
    { "label": "Diesel Fuel, NY Harbor Ultra-Low Sulfur", "value": "WSJ/DIESEL_ULS" },
    { "label": "Crude Oil, Alaska North Slope, Pacific delivery", "value": "WSJ/OIL_AKNS" },
    { "label": "Gasoline, Conventional, Premium NY", "value": "WSJ/GAS_CP" },
    { "label": "Wheat, Hard, Kansas City", "value": "WSJ/WHEAT_KC" },
    { "label": "Barley, top-quality Minneapolis", "value": "WSJ/BARLEY" },
    { "label": "Gold, London p.m. fixing", "value": "WSJ/AU_LPM" },
    { "label": "Gold, London a.m. fixing", "value": "WSJ/AU_LAM" },
    { "label": "Silver, London fixing, spot price", "value": "WSJ/AG_GBP" },
    { "label": "Hams, 17-20 lbs, Mid US FOB", "value": "WSJ/HAMS" },
    { "label": "Natural Gas, Haynesville N. LA", "value": "WSJ/NG_HAYN" },
    { "label": "Silver, Handy & Harman fabric price", "value": "WSJ/AG_HHF" },
    { "label": "Tin, N. Am. solder", "value": "WSJ/TIN" },
    { "label": "Gold, Handy & Harman base price", "value": "WSJ/AU_HHB" },
    { "label": "Raw Sugar FOB", "value": "WSJ/SUGAR_FOB" },
    { "label": "Raw Sugar C&F", "value": "WSJ/SUGAR_CNF" },
    { "label": "Sorghum (Milo), No. 2 Gulf", "value": "WSJ/SORGHUM" },
    { "label": "Gold, Handy & Harman fabric price", "value": "WSJ/AU_HHF" },
    { "label": "Gold, Krugerrand, wholesale", "value": "WSJ/AU_ZAR" },
    { "label": "Gold, Maple Leaf", "value": "WSJ/AU_MPL" },
    { "label": "White Sugar FOB", "value": "WSJ/SUGAR_WHT" },
    { "label": "Soybeans, No. 1 Yellow, Illinois", "value": "WSJ/SOYB_1" },
    { "label": "Burlap, 10-oz, 40-inch NY yard nominal", "value": "WSJ/BURLAP" },
    { "label": "Lard, Chicago", "value": "WSJ/LARD" },
    { "label": "Natural Gas, Transco Zone 6 NY", "value": "WSJ/NG_TRAN6" },
    { "label": "Tallow, Edible, Chicago", "value": "WSJ/TALLOW_E" },
    { "label": "Eggs, Large White, Chicago", "value": "WSJ/EGGS" },
    { "label": "Broiler chickens, dressed 'A' grade", "value": "WSJ/CHKN_A" },
    { "label": "Silver, London fixing, USD equivalent", "value": "WSJ/AG_USD" },
    { "label": "Aluminum, Ryan's Notes", "value": "WSJ/AL_RYN" },
    { "label": "Milk, Non-Fat Dry, Chicago", "value": "WSJ/MILK" },
    { "label": "Silver, Engelhard industrial bullion", "value": "WSJ/AG_EIB" },
    { "label": "Butter, AA Chicago", "value": "WSJ/BUTTER" },
    { "label": "Platinum, Engelhard fabricated products", "value": "WSJ/PL_EFP" },
    { "label": "Soybean Meal, Central Illinois", "value": "WSJ/SOYB_MEAL" },
    { "label": "Corn Oil, Crude Wet/Dry Mill", "value": "WSJ/CORN_OIL" },
    { "label": "Meat-bonemeal, 50% protein, Minneapolis", "value": "WSJ/BONE_MEAL" },
    { "label": "Cotton, 1 1/16 strand lw-md Memphis", "value": "WSJ/COTTON" },
    { "label": "Gold, Austria crown", "value": "WSJ/AU_CRN" },
    { "label": "Steel, Hot-Rolled Coil US, FOB Midwest Mill", "value": "WSJ/STEEL" },
    { "label": "Pork Loins, 13-19 lbs, Mid US", "value": "WSJ/PLOIN" },
    { "label": "Copper, high grade, Comex spot", "value": "WSJ/COPPER" },
    { "label": "Silver Coins, wholesale", "value": "WSJ/AG_CNF" },
    { "label": "Bran, wheat middlings, Kansas City", "value": "WSJ/BRAN" },
    { "label": "Corn gluten feed, Midwest", "value": "WSJ/CORN_FEED" },
    { "label": "Stainless Steel Scrap, US", "value": "WSJ/ST_SCRP" },
    { "label": "Broiler chickens, national composite weighted average price", "value": "WSJ/CHKN_NTL" },
    { "label": "Coffee, Brazilian Composite", "value": "WSJ/COFFEE_BRZL" },
    { "label": "Beef, choice grades 1-3", "value": "WSJ/BEEF_C" },
    { "label": "Hogs, Iowa-South Minnesota average", "value": "WSJ/HOGS" },
    { "label": "Lead, N. Am. Solder", "value": "WSJ/LEAD" },
    { "label": "Natural Gas, Transco Zone 3", "value": "WSJ/NG_TRAN3" },
    { "label": "Natural Gas, Henry Hub", "value": "WSJ/NG_HH" },
    { "label": "Cheddar Cheese, Blocks, Chicago", "value": "WSJ/CHEESE_BLK" },
    { "label": "Gold, Engelhard industrial bullion", "value": "WSJ/AU_EIB" },
    { "label": "Wheat, Spring 14% protein, Minneapolis", "value": "WSJ/WHEAT_MN" },
    { "label": "Natural Gas, Opal", "value": "WSJ/NG_OPAL" },
    { "label": "Coffee, Colombian, NY", "value": "WSJ/COFFEE_CLMB" },
    { "label": "Cattle Hides", "value": "WSJ/HIDES" },
    { "label": "Cotlook 'A' Index", "value": "WSJ/COTLOOK" },
    { "label": "Zinc, N. Am", "value": "WSJ/ZINC" },
    { "label": "Gold, Mexican peso", "value": "WSJ/AU_MXP" },
    { "label": "Tallow, Bleachable, Chicago", "value": "WSJ/TALLOW_B" },
    { "label": "Natural Gas, Marcellus NE PA", "value": "WSJ/NG_MARC" },
    { "label": "Butane, normal, Mont Belvieu, Texas", "value": "WSJ/BUTANE" },
    { "label": "Platinum, Engelhard industrial bullion", "value": "WSJ/PL_EIB" },
    { "label": "Gold, Engelhard fabricated products", "value": "WSJ/AU_EFP" },
    { "label": "Cheddar Cheese, Barrels, Chicago", "value": "WSJ/CHEESE_BRL" },
    { "label": "Silver, Engelhard fabricated products", "value": "WSJ/AG_EFP" },
    { "label": "Natural Gas, Panhandle East", "value": "WSJ/NG_PHE" },
    { "label": "Coal, Powder River Basin", "value": "WSJ/COAL_POWD" },
    { "label": "Propane, tet, Mont Belvieu, Texas", "value": "WSJ/PROPANE" },
    { "label": "Gold, Austria phil", "value": "WSJ/AU_PHL" },
    { "label": "Platinum, free market", "value": "WSJ/PL_MKT" },
    { "label": "Iron Ore, 62% Fe CFR China", "value": "WSJ/FE_TJN" },
    { "label": "Shredded Scrap, US Midwest", "value": "WSJ/SH_SCRP" },
    { "label": "Rice, 5% Broken White, Thailand", "value": "WSJ/RICE_THAI" },
    { "label": "Palladium, Engelhard fabricated products", "value": "WSJ/PA_EFP" },
    { "label": "Coal, Central Appalachia", "value": "WSJ/COAL_CAPP" },
    { "label": "Oats, No.2 Milling, Minneapolis", "value": "WSJ/OATS" },
    { "label": "Cocoa, Ivory Coast", "value": "WSJ/COCOA" },
    { "label": "Wheat, No. 1 Soft White, Portland OR", "value": "WSJ/WHEAT_1" },
    { "label": "Grease, Choice White, Chicago", "value": "WSJ/GREASE" },
    { "label": "Beef, select grades 1-3", "value": "WSJ/BEEF_S" },
    { "label": "Wheat, No. 2 Soft Red, St Louis", "value": "WSJ/WHEAT_2" },
    { "label": "Gold, American Eagle", "value": "WSJ/AU_EGL" },
    { "label": "Flour, Hard Winter, Kansas City", "value": "WSJ/FLOUR" },
    { "label": "Corn, No. 2 Yellow, Central Illinois", "value": "WSJ/CORN_2" },
    { "label": "Cottonseed meal", "value": "WSJ/CTNSD_MEAL" },
    { "label": "Steers, feeder, Oklahoma city average", "value": "WSJ/FEEDER" },
    { "label": "Silver, Handy & Harman base price", "value": "WSJ/AG_HHB" },
    { "label": "Rice, No. 2 Long Grain Milled", "value": "WSJ/RICE_2" },
    { "label": "Corn gluten meal, Midwest", "value": "WSJ/CORN_MEAL" },
    ["Soybean Oil, Crude, Central Illinois", "WSJ/SOYB_OIL"]
]
